Numpy
- Numerical pyhton
- Arrays (similar to list but works 50 times faster)
- Contigous memory location
- Access and manipulation easier (C concept of array)
- written inn C/C++
- ndarray object



In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [11]:
arr = np.array([1, 2, 4, 5, 7])
id(arr), id(arr[0]), id(arr[1])

(2142236718160, 2142239338896, 2142239338896)

In [6]:
arr.itemsize, arr.strides, type(arr)

(4, (4,), numpy.ndarray)

In [7]:
arr.shape

(5,)

In [12]:
for item in arr:
    print(id(item))

2142239338928
2142239339312
2142239338928
2142239339312
2142239338928


In [18]:
arr1 = np.array([[1, 2, 4, 5, 7], [9, 7, 3, 6, 1]])
arr1.itemsize, arr1.strides

(4, (20, 4))

In [15]:
arr1.ndim, arr.ndim

(2, 1)

In [16]:
arr1.size, arr.size

(10, 5)

In [20]:
arr1.dtype, arr.dtype

(dtype('int32'), dtype('int32'))

In [21]:
e = np.arange(15).reshape(3,5)

In [22]:
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
e.size

15

In [25]:
help(np.size)

Help on function size in module numpy:

size(a, axis=None)
    Return the number of elements along a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : int, optional
        Axis along which the elements are counted.  By default, give
        the total number of elements.
    
    Returns
    -------
    element_count : int
        Number of elements along the specified axis.
    
    See Also
    --------
    shape : dimensions of array
    ndarray.shape : dimensions of array
    ndarray.size : number of elements in array
    
    Examples
    --------
    >>> a = np.array([[1,2,3],[4,5,6]])
    >>> np.size(a)
    6
    >>> np.size(a,1)
    3
    >>> np.size(a,0)
    2



In [30]:
ran = np.arange(1, 5, 0.5)
ran

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [31]:
x = np.linspace(0, 2, 9)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])